version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - PORT=${REACT_APP_PORT}
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      - PORT=${BACKEND_PORT}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    env_file:
      - .env

volumes:
  mongodb_data: 